routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/discuss', function () {
    return view('discussion/discuss');
});
Route::get('/discussion/{slug}',[
    'uses'=>'DiscussionController@show',
    'as'=>'discussion'
]);

Route::get('channel/{slug}',[
    'uses'=>'ForumsController@channel',
    'as'=>'channel'
]);

Auth::routes();

Route::get('/forum',[
    'uses'=>'ForumsController@index',
    'as'=>'forum'
]);

Route::get('{provider}/auth',[
    'uses'=>'SocialsController@auth',
    'as'=>'social.auth'
]);

Route::get('/{provider}/redirect',[
    'uses'=>'SocialsController@auth_callback',
    'as'=>'social.callback'
]);


Route::group(['middleware'=>'auth'],function (){
    Route::resource('channels','ChannelsController');

    Route::get('/discussion/create/new',[
        'uses'=>'DiscussionController@create',
        'as'=>'discussion.create'
    ]);
    Route::post('/discussion/store',[
        'uses'=>'DiscussionController@store',
        'as'=>'discussion.store'
    ]);

    Route::post('/discussion/reply/{id}',[
        'uses'=>'DiscussionController@reply',
        'as'=>'discussion.reply'
    ]);
    Route::get('/reply/like/{id}',[
        'uses'=>'LikesController@like',
        'as'=>'reply.like'
    ]);
    Route::get('/reply/unlike/{id}',[
        'uses'=>'LikesController@unlike',
        'as'=>'reply.unlike'
    ]);

    Route::get('/discussion/watch/{id}',[
        'uses'=>'WatchersController@watch',
        'as'=>'discussion.watch'
    ]);
    Route::get('/discussion/unwatch/{id}',[
        'uses'=>'WatchersController@unwatch',
        'as'=>'discussion.unwatch'
    ]);
    Route::get('/discussion/best/reply/{id}',[
        'uses'=>'LikesController@best_answer',
        'as'=>'discussion.best.answer'
    ]);

    Route::get('/discussion/edit/{slug}',[
        'uses'=>'DiscussionController@edit',
        'as'=>'discussion.edit'
    ]);
    Route::post('/discussion/update/{id}',[
        'uses'=>'DiscussionController@update',
        'as'=>'discussion.update'
    ]);

    Route::get('/reply/edit/{id}',[
        'uses'=>'LikesController@edit',
        'as'=>'replies.edit'
    ]);
    Route::post('/reply/update/{id}',[
        'uses'=>'LikesController@update',
        'as'=>'reply.update'
    ]);


});

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    //
    protected $fillable=['title','slug'];

    public function discussions()
    {
        return $this->hasMany('App\Discussion');
    }
}

app/Http/Controllers/ChannelsController.php
<?php

namespace App\Http\Controllers;
use App\Channel;
use Illuminate\Http\Request;
use Session;
class ChannelsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('channels.index')->with('channels',Channel::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('channels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'channel'=>'required'
        ]);

        Channel::create([
            'title'=> $request->channel,
            'slug'=>str_slug($request->channel)
        ]);

        Session::flash('success',"Channel Created");

        return redirect()->route('channels.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Channel::find($id);
        return view('channels.edit')->with('channel',Channel::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $chnnel=Channel::find($id);
        $chnnel->title=$request->channel;
        $chnnel->slug=str_slug($request->channel);
        $chnnel->save();

        Session::flash('success',"Channel edited successfully");
        return redirect()->route('channels.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Channel::destroy($id);
        Session::flash('success','Channel Deleted');
        return redirect()->route('channels.index');
    }
}

resources/views/channels/create.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">Create a new Channel</div>

                    <div class="card-body">
                        <form action="{{route('channels.store')}}" method="post">
                            {{csrf_field()}}
                            <div class="form-group">
                                <input type="text" class="form-control" name="channel">
                            </div>
                            <div class="form-group">
                                <div class="text-center">
                                    <button class="btn btn-success" type="submit"> Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
@endsection

resources/views/channels/edit.blade.php
@extends('layouts.app')

@section('content')
                <div class="card">
                    <div class="card-header">Edit Channel: {{$channel->title}}</div>

                    <div class="card-body">
                        <form action="{{route('channels.update',['channel'=>$channel->id ])}}" method="post">
                            {{csrf_field()}}
                            {{method_field('PUT')}}
                            <div class="form-group">
                                <input type="text" class="form-control" name="channel" value="{{$channel->title}}">
                            </div>
                            <div class="form-group">
                                <div class="text-center">
                                    <button class="btn btn-success" type="submit"> Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
@endsection

resources/views/channels/index.blade.php
@extends('layouts.app')

@section('content')

                <div class="card">
                    <div class="card-header">Channels</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table table-hover">
                            <thead>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    Delete
                                </th>
                            </thead>

                            <tbody>
                                @foreach($channels as $channel)
                                    <tr>
                                        <td>
                                            {{$channel->title}}
                                        </td>

                                        <td>
                                            <a href="{{route('channels.edit',['channel'=>$channel->id])}}" class="btn btn-sm btn-info">Edit</a>
                                        </td>

                                        <td>
                                            <form action="{{route('channels.destroy',['channel'=>$channel->id])}}" method="post">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}
                                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>

                                    @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
@endsection